image: "$CI_REGISTRY_IMAGE/dotnet-sdk:6.0"

stages:
  - tests
  - builds
#  - deploys


.build:
  stage: builds
  script:
    - dotnet publish -c Release -o publish MyProject/MyProject.csproj
    - ls -al publish


test:
  stage: tests
  before_script:
    # rapport junit
    - >
      dotnet add MyProject.Test/MyProject.Test.csproj
      package JUnitTestLogger --version 1.1.0 > /dev/null
    # couverture de code format text
    - dotnet add package coverlet.msbuild
  script:
    - dotnet test /p:CollectCoverage=true || exit 0
    - >
      dotnet test 
      --logger "junit;LogFilePath=$CI_PROJECT_DIR/reports/junit.xml"
      --results-directory:$CI_PROJECT_DIR/reports
      --collect:"XPlat Code Coverage"
      MyProject.Test
  # remontée de rapport intégrables dans gitlab
  artifacts:
    reports:
      junit: reports/junit.xml
      cobertura: "reports/**/coverage.cobertura.xml"
