# image par défaut des jobs du pipeline
# utilisation du registre d'image privé
# utilisation d'une variable d'environnement
image: $CI_REGISTRY_IMAGE/dotnet-sdk:3.1-debian-11

unit test:
  # image spécifique au job
  # image: bitnami/dotnet-sdk:3.1-debian-11
  script:
    - dotnet --info
  tags:
    - myusine