# image par défaut des jobs du pipeline
image: gitlab.myusine.fr:5050/myusine/dev/dotnet-sdk:3.1-debian-11

unit test:
  # image spécifique au job
  # image: bitnami/dotnet-sdk:3.1-debian-11
  script:
    - dotnet --info
  tags:
    - myusine