# image par défaut des jobs du pipeline
# utilisation du registre d'image privé
# utilisation d'une variable d'environnement
image: $CI_REGISTRY_IMAGE/dotnet-sdk:3.1-debian-11

# liste des étapes d'exécution du pipeline
stages:
  - testing
  - building

unit test:
  # association du job à un stage
  stage: testing
  script:
    - dotnet --info
    - exit 1
  tags:
    - myusine

build:
  stage: building
  script:
    - echo "Build"
  tags:
    - myusine

