# image par défaut des jobs du pipeline
# utilisation du registre d'image privé
# utilisation d'une variable d'environnement
image: $CI_REGISTRY_IMAGE/dotnet-sdk:3.1-debian-11

# liste des étapes d'exécution du pipeline
stages:
  - testing
  - building
  - deploying

variables:
  TRIGGER_CACHE: "off"


restore:
  stage: .pre
  script:
    - dotnet restore --packages .nuget
  tags:
    - myusine
  cache:
    key: nuget
    paths:
      - .nuget/
    policy: push
  rules:
    - changes:
        - "**/*.csproj"
    - if: $TRIGGER_CACHE == "on"

unit test:
  stage: testing
  before_script:
    - dotnet restore --packages .nuget
  # /p ... => calcul de la couverture de code au format cobertura (java)
  # --collect => génération du rapport de couv
  # --no-restore => ne pas redemander les dépendances (déjà fait)
  # --logger => génération du rapport de testunitaire au format junit
  # --result-directory => dossier racine des rapports
  script:
    - >
      dotnet test
      /p:CollectCoverage=true 
      /p:CoverletOutputFormat=cobertura 
      --collect:"XPlat Code Coverage"
      --no-restore
      --logger "junit;LogFilePath=reports/test-result.xml" 
      --results-directory:"$CI_PROJECT_DIR/020123/reports"
    - cd 020123/reports/*
    - cat coverage.cobertura.xml
  tags:
    - myusine
  artifacts: 
    expire_in: 1 hour
    paths:
      - 020123/reports/
    reports:
      junit: 020123/reports/test-result.xml
      cobertura: "020123/reports/**/coverage.cobertura.xml"
  cache:
    key: nuget
    untracked: true
    policy: pull

.build:
  stage: building
  script:
    - echo "Build"
  tags:
    - myusine

.prod:
  stage: deploying
  script:
    - echo "Deploy !"
  tags:
    - myusine
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual

