image: "$CI_REGISTRY_IMAGE/dotnet-sdk:6.0"

stages:
  - builds
  - tests
  - deploys

build:
  stage: builds
  script:
    # création d'un artefact (rapport, composant logiciel ...)
    - mkdir build
    - echo "build content" > build/artifact
  # prélèvement de l'artefact
  artifacts:
    expire_in: 1 hour
    paths:
      - build/

test:
  stage: tests
  script:
    # artefact installé par gitlab-runner
    - test -e build/artifact